'use client';
import { useState } from 'react';
import Head from 'next/head';

export default function Home() {
  const [prompt, setPrompt] = useState('');
  const [size, setSize] = useState('medium');
  const [imageURL, setImageURL] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  return (
    <>
      <Head>
        <title>AI Image Generator</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='container'>
        <h1 className='text-center'>Generate Image Through AI!</h1>
        <form
          onSubmit={async e => {
            e.preventDefault();
            if (prompt && size) {
              setIsLoading(true);
              const res = await fetch('/api/generate', {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                },
                body: JSON.stringify({ prompt, size }),
              });
              if (res.ok) {
                const data = await res.json();
                setImageURL(data);
                setError('');
              } else {
                const data = await res.json();
                setImageURL('');
                setError(data);
              }
              setIsLoading(false);
            }
          }}>
          <input type='text' placeholder='Prompt...' value={prompt} onChange={e => setPrompt(e.target.value)} />
          <select value={size} onChange={e => setSize(e.target.value)}>
            <option value='' disabled>
              Select Size
            </option>
            <option value='large'>Large</option>
            <option value='medium'>Medium</option>
            <option value='small'>Small</option>
          </select>
          <button type='submit' aria-busy={isLoading} disabled={isLoading}>
            Generate
          </button>
        </form>
        <div className='image-container'>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          {imageURL && <img src={imageURL} alt='' />}
          {error && <p>{error}</p>}
        </div>
      </main>
    </>
  );
}
